In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('powerplant_data.csv')

In [3]:
df.head()

      AT      V       AP     RH      PE
0   8.34  40.77  1010.84  90.01  480.48
1  23.64  58.49  1011.40  74.20  445.75
2  29.74  56.90  1007.15  41.91  438.76
3  19.07  49.69  1007.22  76.79  453.09
4  11.80  40.66  1017.13  97.20  464.43

In [4]:
df.isnull().sum()

AT    0
V     0
AP    0
RH    0
PE    0
dtype: int64

In [5]:
df.shape

(9568, 5)

In [6]:
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split

In [7]:
X= df.drop(columns='PE', axis=1)
y = df['PE']

In [8]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [9]:
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [10]:
import torch
import torch.nn as nn

In [11]:
X_train_tensor = torch.tensor(X_train_scaled, dtype=torch.float32)
y_train_tensor = torch.tensor(y_train.values, dtype=torch.float32).view(-1, 1)

X_test_tensor = torch.tensor(X_test_scaled, dtype=torch.float32)
y_test_tensor = torch.tensor(y_test.values, dtype=torch.float32).view(-1, 1)

In [12]:
from torch.utils.data import TensorDataset, DataLoader

train_dataset = TensorDataset(X_train_tensor, y_train_tensor)
test_dataset = TensorDataset(X_test_tensor, y_test_tensor)

In [13]:
train_loader = DataLoader(train_dataset, batch_size=32, shuffle=True)
test_loader = DataLoader(test_dataset, batch_size=32)

In [14]:
# Define Deep Learning 

class ANN(torch.nn.Module):
    def __init__(self):
        super().__init__()

        self.model = torch.nn.Sequential(
            # 1st hidden layer
            nn.Linear(X_train.shape[1], 6),
            nn.ReLU(),

            # 2nd Hidden Layer
            nn.Linear(6, 6),
            nn.ReLU(),

            # Output layer
            nn.Linear(6, 1)
        )

    def forward(self, x):
        return self.model(x)

In [15]:
model = ANN()

In [16]:
import torch.optim as optim

criterion = nn.MSELoss()
optimizer = optim.Adam(model.parameters())

In [17]:
epochs = 100

best_val_loss = float('inf')

for epoch in range(epochs):
    model.train()
    train_loss = 0.0

    for xb, yb in train_loader:
        optimizer.zero_grad()

        output = model(xb)
        loss = criterion(output, yb)
        loss.backward()
        optimizer.step()

        train_loss += loss.item()
    epoch_train_loss = train_loss / len(train_loader)

    # validation
    model.eval()
    test_loss = 0.0

    for xb, yb in test_loader:
        with torch.no_grad():
            output = model(xb)
            loss = criterion(output, yb)

            test_loss += loss.item()

    epoch_test_loss = test_loss / len(test_loader)

    print(f"EPOCH: {epoch+1} / {epochs} train_loss: {epoch_train_loss} & test_loss: {epoch_test_loss}")

    #Save_model:
    if epoch_test_loss < best_val_loss:
        best_val_loss = epoch_test_loss
        torch.save(model.state_dict(), 'best_model.pt')

EPOCH: 1 / 100 train_loss: 205830.13919270833 & test_loss: 204344.81744791666
EPOCH: 2 / 100 train_loss: 198680.55872395833 & test_loss: 188384.47239583332
EPOCH: 3 / 100 train_loss: 169292.21809895834 & test_loss: 145846.35859375
EPOCH: 4 / 100 train_loss: 118196.50677083334 & test_loss: 90602.141015625
EPOCH: 5 / 100 train_loss: 67894.1701904297 & test_loss: 49431.60553385417
EPOCH: 6 / 100 train_loss: 37775.85051269531 & test_loss: 28857.87958984375
EPOCH: 7 / 100 train_loss: 23431.595373535158 & test_loss: 19110.919189453125
EPOCH: 8 / 100 train_loss: 16494.448787434896 & test_loss: 14212.036376953125
EPOCH: 9 / 100 train_loss: 12700.475061035157 & test_loss: 11104.368701171876
EPOCH: 10 / 100 train_loss: 9871.75303548177 & test_loss: 8558.951928710938
EPOCH: 11 / 100 train_loss: 7494.891542561849 & test_loss: 6361.725512695312
EPOCH: 12 / 100 train_loss: 5460.920066324869 & test_loss: 4549.884065755208
EPOCH: 13 / 100 train_loss: 3863.8358301798503 & test_loss: 3202.636328125
EPOCH: 14 / 100 train_loss: 2745.2357513427733 & test_loss: 2283.6147318522135
EPOCH: 15 / 100 train_loss: 1976.903343963623 & test_loss: 1662.317978922526
EPOCH: 16 / 100 train_loss: 1452.595287322998 & test_loss: 1228.78790435791
EPOCH: 17 / 100 train_loss: 1073.8638940175374 & test_loss: 906.2943735758464
EPOCH: 18 / 100 train_loss: 792.9833805084229 & test_loss: 666.6505719502767
EPOCH: 19 / 100 train_loss: 587.6247887293498 & test_loss: 482.759600575765
EPOCH: 20 / 100 train_loss: 416.60308005015054 & test_loss: 345.3269223531087
EPOCH: 21 / 100 train_loss: 297.78289976119993 & test_loss: 246.06769104003905
EPOCH: 22 / 100 train_loss: 210.51919655799867 & test_loss: 174.40949732462565
EPOCH: 23 / 100 train_loss: 150.88468283017477 & test_loss: 126.49142710367839
EPOCH: 24 / 100 train_loss: 111.40116823514303 & test_loss: 94.17859592437745
EPOCH: 25 / 100 train_loss: 83.98841193517049 & test_loss: 71.75075817108154
EPOCH: 26 / 100 train_loss: 65.4747134288152 & test_loss: 56.28556496302287
EPOCH: 27 / 100 train_loss: 52.37449772755305 & test_loss: 45.89079472223918
EPOCH: 28 / 100 train_loss: 43.4213128387928 & test_loss: 37.79943772951762
EPOCH: 29 / 100 train_loss: 36.94183105826378 & test_loss: 32.66452981630961
EPOCH: 30 / 100 train_loss: 32.404765196641286 & test_loss: 28.553411277135215
EPOCH: 31 / 100 train_loss: 29.376014006137847 & test_loss: 25.749460951487222
EPOCH: 32 / 100 train_loss: 26.91251806020737 & test_loss: 23.8660844484965
EPOCH: 33 / 100 train_loss: 25.406422873338062 & test_loss: 22.608199087778726
EPOCH: 34 / 100 train_loss: 24.15654254158338 & test_loss: 22.022713152567544
EPOCH: 35 / 100 train_loss: 23.38025132616361 & test_loss: 21.080399974187216
EPOCH: 36 / 100 train_loss: 22.866507995128632 & test_loss: 20.576355727513633
EPOCH: 37 / 100 train_loss: 22.49391041994095 & test_loss: 20.465596373875936
EPOCH: 38 / 100 train_loss: 22.127732888857523 & test_loss: 20.302391417821248
EPOCH: 39 / 100 train_loss: 21.968109742800394 & test_loss: 20.367948277791342
EPOCH: 40 / 100 train_loss: 21.778263898690543 & test_loss: 20.102568483352663
EPOCH: 41 / 100 train_loss: 21.927195111910503 & test_loss: 19.90641730626424
EPOCH: 42 / 100 train_loss: 21.702332504590352 & test_loss: 19.9027508576711
EPOCH: 43 / 100 train_loss: 21.485461497306822 & test_loss: 19.943195231755574
EPOCH: 44 / 100 train_loss: 21.316842488447826 & test_loss: 19.89669108390808
EPOCH: 45 / 100 train_loss: 21.375182723999025 & test_loss: 19.766836404800415
EPOCH: 46 / 100 train_loss: 21.378798604011536 & test_loss: 19.661300961176554
EPOCH: 47 / 100 train_loss: 21.219297643502554 & test_loss: 19.64973923365275
EPOCH: 48 / 100 train_loss: 21.349166059494017 & test_loss: 19.69279079437256
EPOCH: 49 / 100 train_loss: 21.326361294587453 & test_loss: 19.560264054934184
EPOCH: 50 / 100 train_loss: 21.28233410914739 & test_loss: 19.701956089337667
EPOCH: 51 / 100 train_loss: 21.205542866388956 & test_loss: 19.93546211719513
EPOCH: 52 / 100 train_loss: 21.206327617168427 & test_loss: 19.642543649673463
EPOCH: 53 / 100 train_loss: 21.117552761236826 & test_loss: 19.69971438248952
EPOCH: 54 / 100 train_loss: 21.18002688884735 & test_loss: 20.071652110417684
EPOCH: 55 / 100 train_loss: 21.1132945338885 & test_loss: 19.76361737251282
EPOCH: 56 / 100 train_loss: 21.25661726395289 & test_loss: 19.477543131510416
EPOCH: 57 / 100 train_loss: 20.999460991223653 & test_loss: 20.064439741770425
EPOCH: 58 / 100 train_loss: 21.16193822224935 & test_loss: 20.017576932907104
EPOCH: 59 / 100 train_loss: 21.22639482021332 & test_loss: 19.606234709421795
EPOCH: 60 / 100 train_loss: 21.020335117975872 & test_loss: 19.72449256579081
EPOCH: 61 / 100 train_loss: 21.148158689339954 & test_loss: 19.414094924926758
EPOCH: 62 / 100 train_loss: 21.140248395999272 & test_loss: 19.693119184176126
EPOCH: 63 / 100 train_loss: 21.075613911946615 & test_loss: 20.463397185007732
EPOCH: 64 / 100 train_loss: 21.110244846343996 & test_loss: 19.52815769513448
EPOCH: 65 / 100 train_loss: 21.112917566299437 & test_loss: 19.486762539545694
EPOCH: 66 / 100 train_loss: 21.090794909000397 & test_loss: 20.317024183273315
EPOCH: 67 / 100 train_loss: 21.052947294712066 & test_loss: 19.93950983683268
EPOCH: 68 / 100 train_loss: 21.087660578886666 & test_loss: 19.326888179779054
EPOCH: 69 / 100 train_loss: 21.03185595870018 & test_loss: 19.331218433380126
EPOCH: 70 / 100 train_loss: 21.061790891488393 & test_loss: 19.828510014216103
EPOCH: 71 / 100 train_loss: 21.148853743076323 & test_loss: 19.90303244590759
EPOCH: 72 / 100 train_loss: 20.901967253287633 & test_loss: 19.198898458480834
EPOCH: 73 / 100 train_loss: 21.158866767088572 & test_loss: 20.54459212621053
EPOCH: 74 / 100 train_loss: 21.04095443089803 & test_loss: 19.87739819685618
EPOCH: 75 / 100 train_loss: 20.91524828672409 & test_loss: 19.187522276242575
EPOCH: 76 / 100 train_loss: 20.887071442604064 & test_loss: 19.444671853383383
EPOCH: 77 / 100 train_loss: 21.037656811873116 & test_loss: 19.526913571357728
EPOCH: 78 / 100 train_loss: 21.28140335083008 & test_loss: 19.179737536112466
EPOCH: 79 / 100 train_loss: 21.055278527736665 & test_loss: 19.355954138437905
EPOCH: 80 / 100 train_loss: 20.98246724208196 & test_loss: 19.299217446645102
EPOCH: 81 / 100 train_loss: 20.984275086720785 & test_loss: 19.660502123832703
EPOCH: 82 / 100 train_loss: 21.093532180786134 & test_loss: 20.0227166334788
EPOCH: 83 / 100 train_loss: 20.98076117436091 & test_loss: 19.52189146677653
EPOCH: 84 / 100 train_loss: 21.06466114918391 & test_loss: 19.129399474461874
EPOCH: 85 / 100 train_loss: 21.13910393714905 & test_loss: 20.067241938908897
EPOCH: 86 / 100 train_loss: 20.883735406398774 & test_loss: 19.738672320048014
EPOCH: 87 / 100 train_loss: 20.960444724559785 & test_loss: 19.66045209566752
EPOCH: 88 / 100 train_loss: 20.967093551158904 & test_loss: 19.361402638753255
EPOCH: 89 / 100 train_loss: 20.970154015223184 & test_loss: 19.15502626101176
EPOCH: 90 / 100 train_loss: 20.96763966480891 & test_loss: 19.08614166577657
EPOCH: 91 / 100 train_loss: 20.965904676914214 & test_loss: 19.307562907536823
EPOCH: 92 / 100 train_loss: 20.938002145290376 & test_loss: 19.356437492370606
EPOCH: 93 / 100 train_loss: 20.94907765388489 & test_loss: 19.40318104426066
EPOCH: 94 / 100 train_loss: 20.911337800820668 & test_loss: 19.1395170211792
EPOCH: 95 / 100 train_loss: 20.94607899983724 & test_loss: 19.307537190119426
EPOCH: 96 / 100 train_loss: 20.975211743513743 & test_loss: 19.23266603151957
EPOCH: 97 / 100 train_loss: 21.18093011379242 & test_loss: 19.466567198435467
EPOCH: 98 / 100 train_loss: 20.942220026254653 & test_loss: 19.276509634653728
EPOCH: 99 / 100 train_loss: 20.94379588762919 & test_loss: 19.29192026456197
EPOCH: 100 / 100 train_loss: 20.943794616063435 & test_loss: 19.360673427581787

In [18]:
model.load_state_dict(torch.load('best_model.pt'))

In [19]:
model.eval()
with torch.no_grad():
    y_train_pred = model(X_train_tensor)
    y_test_pred = model(X_test_tensor)

    train_mse_loss = criterion(y_train_pred, y_train_tensor)
    test_mse_loss = criterion(y_test_pred, y_test_tensor)

print("train_mse_loss: ", train_mse_loss.item())
print("test_mse_loss: ", test_mse_loss.item())

train_mse_loss:  20.757932662963867
test_mse_loss:  19.092588424682617

In [20]:
from sklearn.metrics import r2_score
score = r2_score(y_test, y_test_pred)
print(score)

0.9332763291107368

In [21]:
pred_df = pd.DataFrame(y_test_pred.numpy(), columns=['Predected'])
actual_df = pd.DataFrame(y_test.values, columns=["Actual"])

pd.concat([pred_df, actual_df], axis=1)

       Predected  Actual
0     435.107086  433.27
1     437.107025  438.16
2     461.125122  458.42
3     476.195221  480.82
4     435.158844  441.41
...          ...     ...
1909  451.368134  456.70
1910  431.671356  438.04
1911  467.342072  467.80
1912  431.152313  437.14
1913  456.567352  456.78

[1914 rows x 2 columns]